{% set name = "psrqpy" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fec06598febde38d88da49ade174b5fd263463298cca965c59a79fb9b9546368

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - ads
    - astropy >=3.2
    - beautifulsoup4
    - matplotlib-base
    - numpy >=1.11
    - packaging
    - pandas >0.21
    - python
    - requests
    - scipy
    - six

test:
  imports:
    - psrqpy

about:
  home: http://www.github.com/mattpitkin/psrqpy/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python module for querying the ATNF pulsar catalogue
  doc_url: https://psrqpy.readthedocs.io/en/latest/
  dev_url: http://www.github.com/mattpitkin/psrqpy/
  description: |
    This package provides a way of querying the ATNF pulsar catalogue.

extra:
  recipe-maintainers:
    - mattpitkin
