{% set name = "psrqpy" %}
{% set version = "1.3.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9446891447d46555134793ccfed40f156b8bbab2ba1b3d1fe7750b2a6e36667

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools_scm >=6.2
  run:
    - ads
    - appdirs
    - astropy-base >=3.2
    - beautifulsoup4
    - matplotlib-base
    - numpy >=1.16
    - packaging
    - pandas >0.21
    - python >={{ python_min }}
    - requests
    - scipy

test:
  imports:
    - psrqpy

about:
  home: https://github.com/mattpitkin/psrqpy/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python module for querying the ATNF pulsar catalogue
  doc_url: https://psrqpy.readthedocs.io/en/latest/
  dev_url: http://www.github.com/mattpitkin/psrqpy/
  description: |
    This package provides a way of querying the ATNF pulsar catalogue.

extra:
  recipe-maintainers:
    - mattpitkin
