{% set name = "psrqpy" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e92346f888d992925e187468e5ed5267d5c62718acd5476971494aa52ae5d724

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - ads
    - astropy >=3.2
    - beautifulsoup4
    - matplotlib-base
    - numpy >=1.11
    - packaging
    - pandas >0.21
    - python >=3.6
    - requests
    - scipy
    - six

test:
  imports:
    - psrqpy

about:
  home: http://www.github.com/mattpitkin/psrqpy/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python module for querying the ATNF pulsar catalogue
  doc_url: https://psrqpy.readthedocs.io/en/latest/
  dev_url: http://www.github.com/mattpitkin/psrqpy/
  description: |
    This package provides a way of querying the ATNF pulsar catalogue.

extra:
  recipe-maintainers:
    - mattpitkin
